apiVersion: apps/v1
kind: Deployment
metadata:
  name: operate 
  labels:
    app: operate 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: operate
  template:
    metadata:
      labels:
        app: operate
    spec:
      serviceAccountName: bigbang
      containers:
      - name: opereate 
        image: rmccarth/operate:latest

