apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: bigbang
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bigbang.simple.deployment
spec:
  scope: Namespaced
  group: simple.deployment
  names:
    kind: BigBang 
    plural: bigbang
    singular: bigbang 
    shortNames:
      - bb 
  versions:
    - name: v1
      served: true
      storage: true
      subresources: { status: { } }  # comment/uncomment for experiments
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Duration
          type: string
          priority: 0
          jsonPath: .spec.duration
          description: For how long the pod should sleep.
        - name: Children
          type: string
          priority: 0
          jsonPath: .status.create_fn.children
          description: The children pods created.
        - name: Message
          type: string
          priority: 0
          jsonPath: .status.create_fn.message
          description: As returned from the handler (sometimes).
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: bigbang 
  name: bigbang-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-binding
  namespace: bigbang
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- kind: ServiceAccount
  name: bigbang-account
  namespace: bigbang
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: bigbang-account
  namespace: bigbang
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operate 
  namespace: bigbang
  labels:
    app: operate 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: operate
  template:
    metadata:
      labels:
        app: operate
    spec:
      serviceAccountName: bigbang-account
      containers:
      - name: operate 
        image: rmccarth/operate:latest
---
apiVersion: simple.deployment/v1
kind: BigBang 
metadata:
  name: bigbang 
  labels:
    somelabel: somevalue
  annotations:
    someannotation: somevalue
spec:
  duration: 1m
  field: value
  items:
  - item1
  - item2
