apiVersion: simple.deployment/v1
kind: BigBang 
metadata:
  name: bigbang 
  labels:
    somelabel: somevalue
  annotations:
    someannotation: somevalue
spec:
  duration: 1m
  field: value
  items:
  - item1
  - item2
